#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: python:3.8

pipelines:
  branches:
    '{develop,master}':
        - step:
            name: Test
            caches:
              - pip
            script:
              - pip install -r requirements.txt
              - pip install pytest
              - pytest
